"""empty message

Revision ID: 98df33225695
Revises: 
Create Date: 2023-06-06 14:39:53.279365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98df33225695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], )
    )
    op.create_table('tastings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('vineyard', sa.String(length=50), nullable=True),
    sa.Column('varietal', sa.String(length=100), nullable=False),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('label_image', sa.String(length=1000), nullable=True),
    sa.Column('other_info', sa.String(length=200), nullable=True),
    sa.Column('sight', sa.String(length=200), nullable=False),
    sa.Column('nose', sa.String(length=200), nullable=False),
    sa.Column('palate', sa.String(length=200), nullable=False),
    sa.Column('thoughts', sa.String(length=200), nullable=True),
    sa.Column('love', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheers',
    sa.Column('tasting_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tasting_id'], ['tastings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tasting_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['tasting_id'], ['tastings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussions')
    op.drop_table('cheers')
    op.drop_table('tastings')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
